### ISSUE TITLE
Netlayer IP is locked and leads to incorrect Behavior

### ISSUE THREAD

**Issue by kooperGit** [strath-sdr/rfsoc_qsfp_offload#1]
After running make command I am getting following error, 

```
WARNING: [Vivado 12-4802] The synthesis checkpoint for IP '/home/tattva-07/Documents/RFSOC_4X2_PYNQ/Offload/board_new/rfsoc_qsfp_offload/boards/RFSoC4x2/rfsoc_offload/rfsoc_offload/rfsoc_offload.srcs/sources_1/bd/block_design/ip/block_design_util_vector_logic_0_0/block_design_util_vector_logic_0_0.xci' is not generated and IP is locked. An out-of-context (OOC) run will be created and/or launched, but synthesis may not be able to complete or could result in incorrect behavior.
Please select 'Report IP Status' from the 'Tools/Report' menu or run Tcl command 'report_ip_status' for more information.
WARNING: [Vivado 12-4802] The synthesis checkpoint for IP '/home/tattva-07/Documents/RFSOC_4X2_PYNQ/Offload/board_new/rfsoc_qsfp_offload/boards/RFSoC4x2/rfsoc_offload/rfsoc_offload/rfsoc_offload.srcs/sources_1/bd/block_design/ip/block_design_util_vector_logic_1_0/block_design_util_vector_logic_1_0.xci' is not generated and IP is locked. An out-of-context (OOC) run will be created and/or launched, but synthesis may not be able to complete or could result in incorrect behavior.
Please select 'Report IP Status' from the 'Tools/Report' menu or run Tcl command 'report_ip_status' for more information.
WARNING: [Vivado 12-4802] The synthesis checkpoint for IP '/home/tattva-07/Documents/RFSOC_4X2_PYNQ/Offload/board_new/rfsoc_qsfp_offload/boards/RFSoC4x2/rfsoc_offload/rfsoc_offload/rfsoc_offload.srcs/sources_1/bd/block_design/ip/block_design_zynq_ultra_ps_e_0_0/block_design_zynq_ultra_ps_e_0_0.xci' is not generated and IP is locked. An out-of-context (OOC) run will be created and/or launched, but synthesis may not be able to complete or could result in incorrect behavior.
Please select 'Report IP Status' from the 'Tools/Report' menu or run Tcl command 'report_ip_status' for more information.
ERROR: [Vivado 12-4756] Launch of runs aborted due to earlier errors while preparing sub-designs for run execution.
INFO: [Common 17-206] Exiting Vivado at Tue Aug  1 15:45:27 2023...
Makefile:10: recipe for target 'bitstream' failed
make[1]: *** [bitstream] Error 1
make[1]: Leaving directory '/home/tattva-07/Documents/RFSOC_4X2_PYNQ/Offload/board_new/rfsoc_qsfp_offload/boards/RFSoC4x2/rfsoc_offload'
Makefile:18: recipe for target 'vivado_prj' failed
make: *** [vivado_prj] Error 2

```
I am using vivado 2021.1 and I didn't modify anything. When I opened the QSFP-Offload project in vivado Netlayer IP is locked and whenever I upgrade IP from IP Status it was staying not upgraded and was still locked. It says that this IP's are not supported for 48dr part number (RFSoC4x2 part number) its in below image.

![Error](https://github.com/strath-sdr/rfsoc_qsfp_offload/assets/140806676/ebd674ad-0a52-45bd-ac6e-969c7397ec6e)

And following is the error I am getting whenever I tried to generate HDL wrapper,

![validate_error](https://github.com/strath-sdr/rfsoc_qsfp_offload/assets/140806676/b661c0c1-067e-4c47-b753-8b49f1b56a3e)

And following is the error when I tried to generate output after upgrading IP,

![upgrade_error](https://github.com/strath-sdr/rfsoc_qsfp_offload/assets/140806676/8031636b-bec3-45d2-b32a-ea96551d8b68)

It would be great if someone could help me out.
Thanks in Advance.

**Comment by dnorthcote** [comment]
Hi @marsiau 

Can you have a gander at this issue,

Dave.

**Comment by marsiau** [comment]
Hello,

Have you applied the [Y2K22](https://support.xilinx.com/s/article/76960?language=en_US) patch to your Vivado installation?

Could you start with a fresh repo clone and run:
```
make patch
make build_ip
make vivado_prj
```

I think ```make patch``` is the missing bit in your case. I removed it from ```make all``` due to errors when it is run more than once. Will make it more clear in the README.

Cheers,
Marius

**Comment by dnorthcote** [comment]
Hi @kooperGit 

Can you confirm if your issue is resolved?

Thanks,
Dave.

**Comment by kooperGit** [comment]
Hi @dnorthcote ,

Sorry for my late reply. Yes I was able to resolve the issue by following steps provided by @marsiau in a fresh start.

**Comment by dnorthcote** [comment]
@marsiau 

Can you update the repo to fix this issue?

Thanks,
Dave.

**Comment by marsiau** [comment]
@dnorthcote 

Updated, should be good to close.

Cheers,
Marius.
