### ISSUE TITLE
RFSoC Boards other than 4x2

### ISSUE THREAD

**Issue by jswoboda** [strath-sdr/rfsoc_qsfp_offload#3]
Can this be run using different boards like a ZCU208 or ZCU216?

**Comment by dnorthcote** [comment]
Hi @jswoboda 

The design could be implemented on the ZCU208 or ZCU216. However, we haven't done this and don't intend to at the moment.

You could leverage the x4 SFP ports on these development boards to send 100Gb/s data to the Mellanox card. You may need an adapter such as a x4 SFP to QSFP fibre cable.

Kind regards,
David.
