### ISSUE TITLE
Error during Vivado synthesis: named port connection 'ap_clk' does not exist for instance 'network_layer_bd_i' of module 'network_layer_bd'

### ISSUE THREAD

**Issue by WeiCheng14159** [strath-sdr/rfsoc_qsfp_offload#4]
![image](https://github.com/strath-sdr/rfsoc_qsfp_offload/assets/12271541/dd089c21-7742-46bc-b435-001eaefebe21)

Thank you for creating this open-source example for the RFSoC platform! I replicated your design by going through the instructions and was able to recreate the block design in Vivado; however, I encountered the above error during the synthesis process. I am using Vivado 2020.2 (not exactly 2021.2) and I have already acquired the CMAC license from Xilinx. I wonder if this error is caused by not applying some of the patches?

**Comment by marsiau** [comment]
Hello,

There seems to be an issue with the networklayer submodule. Make sure to clone this repo with ```--recursive``` flag and run  ```make patch``` (needed only once). This should make the networklayer ip compatible with RFSoC.
According to the [xup_vitis_network_example](https://github.com/xilinx/xup_vitis_network_example?tab=readme-ov-file#tools) tools bellow version 2021.1 are not supported for this IP.

Cheers,
Marius

**Comment by WeiCheng14159** [comment]
Thanks for the info! I switched to Vivado 2021.1 and was able to successfully synthesize the design using the ```make``` command. However, as I tried to edit and synthesize the design in Vivado GUI but it still fail with the same error message above. Do you have ideas why the it works in command line but not in Vivado GUI?

**Comment by marsiau** [comment]
Hey, I can't recreate your issue. Could you share the exact steps you're taking and which OS you're running?
