### ISSUE TITLE
Passing path to bitstream file to Overlay constructor raises ValueError

### ISSUE THREAD

**Issue by NBoumakis** [strath-sdr/rfsoc_qsfp_offload#5]
Good morning, good evening and everything in between (depending on your timezone),

I have noticed that when instantiating an `rfsoc_qsfp_offload.overlay.Overlay` object and passing the path to a bitstream file to the constructor, a ValueError exception is raised. After some investigation I found that when validating that the file exists, `os.path.isdir` is being used. However, since we are supposed to pass the path to the bitstream file and not a directory, the check in `boards/RFSoC4x2/rfsoc_qsfp_offload/drivers/overlay.py:26` fails. Shouldn't that line be using `os.path.isfile` instead?

Thanks in advance

**Comment by marsiau** [comment]
Hello,

This should be fixed now!
Please let me know if it works.

Cheers,
Marius
